### ISSUE TITLE
Add wavemaker.cards and 4thewords.com

### ISSUE THREAD

**Issue by wolfsgrove** [indentlabs/fiction-tools#7]
Hi!

I've enjoyed using https://wavemaker.cards in the past, and https://4thewords.com has helped to make writing routine. Both would be under writing tools/word processors, although Wavemaker has other tools as well (like cards and mindmaps).

Wavemaker is a free PWA that has an optional Google Drive sync (otherwise the content is saved in the browser database, so regular backups are advised).

4thewords is a gamified writing and publishing platform with a subscription model and a free trial.

**Comment by drusepth** [comment]
Thanks for the suggestions; these look awesome! I'll get them added to the list soon. :)

**Comment by drusepth** [comment]
They're both added! Thanks again for the suggestions; if you have any more, please do let me know! :)
